version: "3"

services:
  v2ray:
    image: v2fly/v2fly-core:v5.1.0
    container_name: v2ray_upstream
    restart: always
    environment:
      - v2ray.vmess.aead.forced=false
    command: [ "v2ray","run", "-c", "/etc/v2ray/config.json" ]
    ports:
      - 80:80        # vmess
      - 100:100      # shadowsocks
      - 1355:1355    # vless
      - 13555:13555  # vless-tls
      # - 84:84
      # - 85:85
      # - 86:86
    volumes:
      - ./config/:/etc/v2ray/:ro