version: "3"

services:
  v2ray:
    image: ghcr.io/miladrahimi/v2ray:latest
    container_name: v2ray_client
    restart: always
    command: [ "v2ray", "-config=/etc/v2ray/config.json" ]
    ports:
      - 127.0.0.1:${SOCKS_PORT:-1010}:1010
      - 127.0.0.1:${HTTP_PORT:-1110}:1110
    volumes:
      - ./config/:/etc/v2ray/
      - ./logs:/var/log/v2ray/