version: "3"

services:
  v2ray:
    image: v2fly/v2fly-core:v5.1.0
    container_name: v2ray_client
    restart: always
    command: [ "v2ray","run", "-c", "/etc/v2ray/config.json" ]
    ports:
      - 1081:1081
      - 1082:1082
      - 1083:1083
      - 1084:1084
      - 1085:1085
      - 1086:1086
      - 8118:8118
    volumes:
      - ./config/:/etc/v2ray/:ro